amqp:
    exchange:
        transactions: transactions.topic
    queue:
        transactionHistory: transactionHistory.queue
    routing:
        key: transaction.complete
server:
    port: 8082
spring:
    application:
        name: vault
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Marengs
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/vault_db
        username: root
    flyway:
        baseline-on-migrate: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
transaction:
    validator:
        url: http://localhost:8081/transaction
