amqp:
    exchange:
        transactions: transactions.topic
    queue:
        transactionHistory: transactionHistory.queue
    routing:
        key: transaction.complete
server:
    port: 8082
spring:
    config:
        import: "optional:consul:"
    cloud:
      consul:
        config:
            format: yaml
            default-context: defaults
            data-key: application.yml
            prefixes: config
    application:
        name: vault
    datasource:
        # Creates the database in a file
        url: jdbc:h2:file:~/vault;AUTO_SERVER=TRUE;NON_KEYWORDS=USER;
        username: sa
    flyway:
        baseline-on-migrate: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
logging:
    level:
        org.springframework.amqp.rabbit.connection.CachingConnectionFactory: WARN