
server:
    port: 8085
spring:
    application:
        name: item
    config:
        import: "optional:consul:"
    cloud:
        consul:
            config:
                format: yaml
                default-context: defaults
                data-key: application.yml
                prefixes: config
    datasource:
        # Creates the database in a file
        url: jdbc:h2:mem:item;NON_KEYWORDS=USER;
        username: sa
    jpa:
        show-sql: true
logging:
    level:
        org.springframework.amqp.rabbit.connection.CachingConnectionFactory: WARN