server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      config:
        format: yaml
        default-context: defaults
        data-key: application.yml
        prefixes: config
      enabled: true
      discovery:
        query-passing: true
    gateway:
      routes:
        - id: vault
          uri: lb://vault/
          predicates:
            - Path=/vault/**, /vaultAccount/**, /vaultItem/**
        - id: transactionValidator
          uri: lb://transactionValidator/
          predicates:
            - Path=/transaction/**
        - id: account
          uri: lb://account/
          predicates:
            - Path=/account/**
        - id: item
          uri: lb://item/
          predicates:
            - Path=/item/**
        - id: transactionHistory
          uri: lb://transactionHistory/
          predicates:
            - Path=/history/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET,POST,DELETE

logging:
  level:
    org.springframework.amqp.rabbit.connection.CachingConnectionFactory: WARN
# Uncomment the configuration below if you want to enable route matching logs
#logging:
#  level:
#    org.springframework.cloud.gateway.handler.predicate: trace
