server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    consul:
        enabled: true
        discovery:
          query-passing: true
    gateway:
      routes:
        - id: vault
          uri: lb://vault/
          predicates:
            - Path=/vault/**
        - id: transactionValidator
          uri: lb://transactionValidator/
          predicates:
            - Path=/transaction
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET,POST
management:
  tracing:
    sampling:
      probability: 1.0

# Uncomment the configuration below if you want to enable route matching logs
#logging:
#  level:
#    org.springframework.cloud.gateway.handler.predicate: trace
