###
POST {{host}}/transaction/validate

### GetAccountIdFromItem : check response status is 200
GET {{host}}/item/1

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
POST {{host}}/account/transfer/credit

###
GET {{host}}/vault/all

###
DELETE {{host}}/vault/delete/{{vaultId}}

###
GET {{host}}/vault/exists/{{vaultId}}

###
GET {{host}}/vault/item/{{id}}

###
POST {{host}}/vault/new/{{accountId}}

###
POST {{host}}/vault/offer

###
POST {{host}}/vault/transfer

###
GET {{host}}/{{vaultId}}

###
POST {{host}}/{{vaultId}}/item/deposit/{{itemId}}

###
GET {{host}}/{{vaultId}}/item/withdraw/{{itemId}}

###
GET {{host}}/vault/{{vaultId}}/items

###
GET {{host}}/vaultItem/{{id}}

###
GET {{host}}/vaultItem/{{id}}/vault

###
GET {{host}}/vaultAccount/{{id}}

###
GET {{host}}/vaultAccount/{{id}}/vaults