
// CREATE A NEW TADE-OFFER.
POST http://localhost:8000/vault/offer
Content-Type: application/json

{
  "itemId": 15,
  "fromVaultId": 1,
  "toVaultId": 3,
  "type": "SELL",
  "price": 1000
}

<> 2023-12-12T215523.200.json
<> 2023-12-12T215458.200.json

###
// ACCEPT TRADE OFFER WITH TRANSACTION ID.
GET http://localhost:8000/transaction/accept/1

###
// DECLINE TRADE OFFER WITH TRANSACTION ID.
GET http://localhost:8000/transaction/decline/1

###
// GET ALL INCOMING TRADE OFFERS WITH ACCOUNT ID.
GET http://localhost:8000/transaction/incoming/1

<> 2023-12-12T220355.200.json
<> 2023-12-12T220230.200.json

###
// GET ALL OUTGOING TRADE OFFERS WITH ACCOUNT ID.
GET http://localhost:8000/transaction/outgoing/1