volumes:
  vault_db:
    driver: local
services:
  frontent:
    container_name: frontend
    image: rikatob/frontend:latest
    ports:
      - "8888:8888"
    networks:
      - microservices

  rabbitmq-dev:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - microservices

  zipkin-dev:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - '9411:9411'
    networks:
      - microservices

  consul-dev:
    image: consul:1.15.4
    container_name: consul
    ports:
      - '8500:8500'
      - '8600:8600/udp'
    command: 'agent -dev -node=csgoBank -client=0.0.0.0 -log-level=INFO'
    networks:
      - microservices

  consul-importer:
    image: rikatob/consul-importer:1.0
    depends_on:
      - consul-dev
    networks:
      - microservices

  gateway:
    image: rikatob/gateway:0.0.1-SNAPSHOT
    ports:
      - '8000:8000'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - rabbitmq-dev
      - consul-importer
    networks:
      - microservices

  vault_db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=Marengs
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - microservices

  vault:
    image: rikatob/vault:0.0.1-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - gateway
      - vault_db
      - rabbitmq-dev
    networks:
      - microservices

  transactionValidator:
    image: rikatob/transaction-validator:0.0.1-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - vault_db
      - gateway
      - rabbitmq-dev
    networks:
      - microservices
  account:
    image: rikatob/account:0.0.1-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - vault_db
      - gateway
      - rabbitmq-dev
    networks:
      - microservices

  transactionHistory:
    image: rikatob/transaction-history:0.0.1-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - vault_db
      - gateway
      - rabbitmq-dev
    networks:
      - microservices

  item:
    image: rikatob/item:0.0.1-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - vault_db
      - gateway
      - rabbitmq-dev
    networks:
      - microservices

  logs:
    image: rikatob/logs:0.0.1-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - gateway
      - rabbitmq-dev
    networks:
      - microservices

networks:
  microservices:
    driver: bridge