amqp:
    exchange:
        transactions: transactions.topic
    queue:
        transactionHistory: transactionHistory.queue
    routing:
        key: transaction.complete

spring:
    application:
        name: transactionHistory
    config:
        import: "optional:consul:"
    cloud:
        consul:
            config:
                format: yaml
                default-context: defaults
                data-key: application.yml
                prefixes: config
    datasource:
        # Creates the database in a file
        url: jdbc:h2:file:~/vault;AUTO_SERVER=TRUE;NON_KEYWORDS=USER;
        username: sa
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
logging:
    level:
        org:
            springframework:
                amqp:
                    rabbit:
                        core:
                            RabbitAdmin: DEBUG
                        connection.CachingConnectionFactory: WARN